# === Identificación del proyecto ===
sonar.projectKey=trabajo_docente_mid
sonar.projectName=trabajo_docente_mid
sonar.projectVersion=1.0

# === Directorios del código fuente ===
sonar.sources=.

# === Exclusiones (archivos o carpetas que no se analizan) ===
sonar.exclusions=swagger/**,routers/**,database/**

# === Configuración de pruebas ===
sonar.tests=.
sonar.test.inclusions=**/*_test.go

# === Lenguaje y codificación ===
sonar.sourceEncoding=UTF-8