appname = trabajo_docente_mid
httpport = ${TRABAJO_DOCENTE_MID_HTTPPORT}
runmode = ${TRABAJO_DOCENTE_MID_RUNMODE||prod}
parameterStore = ${PARAMETER_STORE}
copyrequestbody = true
EnableDocs = true
StaticPath = ${TRABAJO_DOCENTE_MID_STATIC_PATH}
TercerosService = ${TERCEROS_SERVICE}
ParametroService = ${PARAMETRO_SERVICE}
PlanTrabajoDocenteService = ${PLAN_TRABAJO_DOCENTE_SERVICE}
HorarioService = ${HORARIO_SERVICE}
EspaciosAcademicosService = ${ESPACIO_ACADEMICO_SERVICE}
ProyectoAcademicoService = ${PROYECTO_ACADEMICO_SERVICE}
OikosService = ${OIKOS_SERVICE}
AcademicaEspacioAcademicoService = ${ACADEMICA_ESPACIO_ACADEMICO_SERVICE}